### ISSUE TITLE
Device unsupported cmd / CMDInvalidException

### ISSUE THREAD

**Issue by CaroGross** [RfidResearchGroup/ChameleonUltra#93]
Hi everybody, 

I just received my chameleon ultra in the mail and wanted to test it out. So I installed the cli from this repo on my MacBook. However, many of the commands don't seem to work for me at all.
For example, when I issue the command `hw battery`, I get the following trace:

`[USB] chameleon --> hw  battery
CLI exception: Traceback (most recent call last):
  File "/Users/c/ChameleonUltra/software/script/chameleon_cli_main.py", line 164, in startCLI
    unit.on_exec(args_parse_result)
  File "/Users/c/ChameleonUltra/software/script/chameleon_cli_unit.py", line 1296, in on_exec
    resp = self.cmd.battery_informartion()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/c/ChameleonUltra/software/script/chameleon_utils.py", line 56, in error_throwing_func
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/c/ChameleonUltra/software/script/chameleon_cmd.py", line 755, in battery_informartion
    return self.device.send_cmd_sync(DATA_CMD_GET_BATTERY_INFO, 0x00)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/c/ChameleonUltra/software/script/chameleon_com.py", line 338, in send_cmd_sync
    raise CMDInvalidException(f"Device unsupported cmd: {cmd}")
chameleon_com.CMDInvalidException: Device unsupported cmd: 1025`

Do I need to update the firmware? 
Thank you so much!

**Comment by doegox** [comment]
oh yes, production firmware is very old, at the scale of this recent project :D
hopefully one day we will handle firmware<>client versions discrepancies in a nicer way.
See https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/docs/firmware.md how tu update
